config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root 'projects#index'

  get '/home' => 'static_pages#home'
  get '/about' => 'static_pages#about'

  get '/downloads' => 'projects#downloads'
  get '/masterindex' => 'projects#masterIndex'

  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/project.rb
class Project < ApplicationRecord
	before_validation :sanitize, :slugify

	mount_uploader :thumbnail, ThumbnailUploader
	mount_uploader :download, DownloadUploader

	def slugify
		self.slug = self.title.downcase.gsub(" ", "-")
	end

	def sanitize
		self.title = self.title.strip
	end
	
	def to_param
			slug
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	#ADMIN_USERNAME and PASSWORD are set in the credentials file by running "EDITOR=nano rails credentials:edit"
	ADMIN = { Rails.application.credentials.ADMIN_USERNAME => Rails.application.credentials.ADMIN_PASSWORD }
	before_action :authenticate, except: [:index, :show, :downloads]

  def index
		  @projects = Project.order(:created_at => :asc).paginate(page: params[:page], per_page: 10)
  end

  def downloads
		  @projectDownloads = Project.order(:created_at => :asc).paginate(page: params[:page], per_page: 15)
  end

  def masterIndex
		  @projects = Project.order(:created_at => :asc).paginate(page: params[:page], per_page: 20)
  end

  def show
	  @project = Project.find_by(slug: params[:id])
  end

  def new
	  @project = Project.new
  end

  def create
	  @project = Project.new(project_params)
	  if @project.valid?
		  @project.save
	  end
	  redirect_to @project
  end

  def edit
	  @project = Project.find_by(slug: params[:id])
  end

  def update
	  @project = Project.find_by(slug: params[:id])
	  @project.update(project_params)
	  redirect_to @project
  end

  def destroy
	  @project = Project.find_by(slug: params[:id])
	  @project.destroy
  end

  private
  def authenticate
		  authenticate_or_request_with_http_digest do |username|
				  ADMIN[username]
		  end
  end

  def project_params
	  params.require(:project).permit(:title, :body, :thumbnail, :published, :download, :downloadDescription, :description, :tags)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Derekthemaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, intiial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</style>
  </head>

  <body>
		  <nav class="navbar">
				  <div class="container">
						  <div class="navbar-brand">
								  <a class="navbar-item" href="/" style="font-weight:bold">
										  Derekthemaker
								  </a>
								  <span class="navbar-burger burger" data-target="navMenu">
										  <span></span>
										  <span></span>
										  <span></span>
								  </span>
						  </div>
						  <div id="navMenu" class="navbar-menu">
								  <div class="navbar-end">
										  <a href="/" class="navbar-item" "is-active">Home</a>
										  <a href="/downloads" class="navbar-item">Downloads</a>
										  <a href="/about" class="navbar-item">About</a>
								  </div>
						  </div>
				  </div>
		  </nav><br>
		<script type="text/javascript">
				(function() {
						var burger = document.querySelector('.burger');
						var nav = document.querySelector('#'+burger.dataset.target);

						burger.addEventListener('click', function(){
								burger.classList.toggle('is-active');
								nav.classList.toggle('is-active');
						});
				})();
		</script>
		<div class="container">
			<%= yield  %>
		</div>
  </body>

  <footer id="footer">
	  <div class="content has-text-centered">
		  <p>
			  This website is still a work in progress. More content and UI tweaks coming soon
		  </p>
	  </div>
  </footer>
</html>

app/views/projects/_form.html.erb
<div id="project-form">
	<%= form_for @project do |f|  %>
		<%= f.label :title  %><br>
		<%= f.text_field :title  %><br>
		<%= f.label :thumbnail  %><br>
		<%= f.file_field :thumbnail  %><br>
		<%= f.label :body  %><br>
		<%= f.cktext_area :body  %><br>
		<%= f.label :description  %><br>
		<%= f.text_field :description  %><br>
		<%= f.label :download  %><br>
		<%= f.file_field :download  %><br>
		<%= f.label :downloadDescription  %><br>
		<%= f.text_field :downloadDescription  %><br>
		<%= f.label :tags  %><br>
		<%= f.text_field :tags  %><br>
		<%= f.label :published   %>
		<%= f.check_box :published  %><br>
		<%= f.submit  %>
	<% end  %>
</div>

app/views/projects/_projects.html.erb
<% @projects.each do |project|  %>
			<% if project.published  %>
					<a href="<%= project_path(project)  %>">
							<div class="card">
										<% if not project.thumbnail.file.nil?  %>
											<div class="card-image">
												<figure class="image">
													<%= image_tag(project.thumbnail.url)  %>
												</figure>
											</div>
										<% end  %>
								<div class="card-content">
										<h4 class="title is-4"><%= project.title  %></h4><hr>
										<div class="content">
											<p><%= project.description  %></p>
										</div>
										<footer style="text-align: right">
												<p>	<%= project.created_at.to_time.strftime('Published: %B %e at %l:%M %p')  %></p>
										</footer>
								</div>
							</div>
					</a><br>
			<% end  %>
<% end  %>

app/views/projects/downloads.html.erb
<div class="container has-text-centered">
		<h1>Downloads</h1>
</div>

<% @projectDownloads.each do |project|  %>
		<% if not project.download.file.nil? and project.published %>
			<div class="card">
					<header class="card-header">
							<h1 class="card-header-title is-centered">
									<%= project.title  %>
							</h1>
					</header>
					<div class="card-content">
							<div class="content has-text-centered">
										<%= project.downloadDescription  %>
							</div>
					</div>
					<footer class="card-footer">
							<span class="card-footer-item has-text-centered">
									<a href="<%= project_url(project)  %>">Read Post</a>
							</span>
							<span class="card-footer-item has-text-centered">
									<p style="display:inline">Download:&nbsp;</p>
									<a href="<%= project.download.url  %>"><%= project.download.file.filename  %></a>
							</span>
					</footer>
			</div><br>
		<% end  %>
<% end  %>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<%= render 'form'  %>

app/views/projects/index.html.erb
<!--<section class="hero is-primary">
		<div class="hero-body">
				<div class="container has-text-centered">
						<h1 class="title">
								Projects
						</h1>
				</div>
		</div>
</section><br>-->
<div id="main-title">
		<h1 class="title is-4">Cool Stuff I've Made</h1>
</div>
<div class="columns">
		<div class="column">
				<%= render 'projects'  %>
		</div>
</div>

<%= will_paginate @projects  %>

app/views/projects/masterIndex.html.erb
<h1>Master Projects</h1>

<% @projects.each do |project|  %>
		<div class="card">
			<header class="card-header">
					<p class="card-header-title">
							<%= project.title  %>
					</p>
			</header>
			<footer class="card-footer">
							<%= link_to 'Destroy', project_path(project),
									data: { :confirm => 'Are you sure?' }, :method => :delete,
									:class => "card-footer-item"%>
							<%= link_to 'Edit', edit_project_path(project),
									:class => "card-footer-item"%>

		</footer>
		</div><br>
<% end  %>

<%= will_paginate @projects  %>

app/views/projects/new.html.erb
<h1>Create new project</h1>
<%= render 'form'  %>

app/views/projects/show.html.erb
<div class="container project-show-page">
		<section class="hero is-dark" >
				<div class="hero-body" >
						<h1 class="title">
							<%= @project.title  %>
						</h1>
						<h6 class="subtitle">
							<%= @project.created_at.to_time.strftime('Published: %B %e,&nbsp; %Y').html_safe  %>
						</h6>
				</div>
		</section>
</div>
<div class="project-show-page" id="project-body">
		<% if not @project.thumbnail.file.nil?  %>
				<%= image_tag(@project.thumbnail.url) %>
		<% end  %>
		<%= raw @project.body  %><hr>
		<% if not @project.download.file.nil?  %>
				<div class="has-text-centered">
						<p style="display:inline">Download project files here: </p><a href="<% @project.download.url  %>"><%= @project.download.file.filename  %></a><hr>
				</div>
		<% end  %>
</div>

app/views/static_pages/about.html.erb
<div class="container has-text-centered">
	<h1 class="title">
		About Me
	</h1>
</div>
<div class="container" id="about">
		<p>Hi, I'm Derek, and I'm a DIY guy, or a "Maker". That means I make things, all kinds of things. I went to a technical college and got two diplomas in machining. But, I'm also a practiced carpenter, and software developer. I make things out of metal, wood, random electronic components, and really anything else. </p>
		<p>If you like what you see here, and want to help keep this site running, consider throwing 0.001 ether my way.<br>My Ether address: 0x548D34b05915be1F024c60F1a5796AA084A99800</p>
</div><br>


<div class="container has-text-centered">
	<h1 class="title">
		About This Site
	</h1>
</div>
<div class="container" id="about">
		<p>
				I said I'm a DIY guy, and this website is no exception. I built this site with Ruby on Rails and host it on a Linode server, running Ubuntu 18.04, Bionic Beaver(amazing OS name). The web app is served with Nginx+Phusion Passenger. This site would not be possible without any of these frameworks/applications, and I like giving them their due credit.
		</p>
		<p>
				You can read more about all of these things, at the links provided here.<br>
				<a href="https://www.rubyonrails.org" target="_blank">Ruby On Rails</a><br>
				<a href="https://www.ubuntu.com" target="_blank">Ubuntu</a><br>
				<a href="https://www.linode.com" target="_blank">Linode</a><br>
				<a href="https://www.nginx.org" target="_blank">Nginx</a><br>
				<a href="https://www.phusionpassenger.com" target="_blank">Phusion Passenger</a><br>
		</p>
</div>